language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      os: linux
    - rust: nightly
      os: linux
    - rust: stable
      os: osx
    - rust: nightly
      os: osx
  allow_failures:
    - rust: stable

install:
    - wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1d.tar.gz
    - tar xvfz OpenSSL_1_1_1d.tar.gz && cd openssl-OpenSSL_1_1_1d
    - if [ $TRAVIS_OS_NAME = "linux" ]; then ./Configure linux-x86_64 --prefix=$HOME/installed_openssl; fi
    - if [ $TRAVIS_OS_NAME = "osx" ]; then ./Configure darwin64-x86_64-cc --prefix=$HOME/installed_openssl; fi
    - make && make install_sw && cd ..
    - export PATH=$HOME/installed_openssl/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/installed_openssl/lib:$LD_LIBRARY_PATH

script:
    - cargo test
    - cargo test --features early-data
      # - cd examples/server
      # - cargo check
      # - cd ../../examples/client
      # - cargo check
